services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  bot:
    build: ./client
    depends_on:
      - api
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    restart: unless-stopped

volumes:
  ollama_data:
